### ISSUE TITLE
jax.abstract_arrays.ShapedArray is deprecated

### ISSUE THREAD

**Issue by mlefkir** [dfm/jax-finufft#17]
Hi,

Starting with jax 0.4.16 ```jax.abstract_arrays.ShapedArray``` is deprecated and the following line should be used

```python
from jax.core import ShapedArray
```
See: https://github.com/google/jax/blob/main/CHANGELOG.md

Can you add modify this for a new release?

Thanks,

**Comment by dfm** [comment]
I'd be happy to review a PR for this! Thanks.

**Comment by lgarrison** [comment]
Closed by #18.
