### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by samaktbo** [dfm/jax-finufft#5]
I am having trouble installing jax-finuff even with the instructions on the home page. The installation fails with

ERROR: Failed building wheel for jax-finufft
Failed to build jax-finufft
ERROR: Could not build wheels for jax-finufft, which is required to install pyproject.toml-based projects

**Comment by dfm** [comment]
Please share _exactly_ what steps you ran and the specs of your system (platform, architecture, Python version, etc.) so that I can help debug.

**Comment by dfm** [comment]
You _might_ also be able to just install using `python -m pip install jax-finufft` because there are wheels available for linux and macos x86_64.

**Comment by samaktbo** [comment]
I am installing on the server so I ran
conda create -p /path/to/jax-finufft -c conda-forge python=3.9 numpy scipy fftw
to create the environment at a specific location. Then I activated the environment and ran 

python -m pip install "jax[cpu]"
git clone --recursive https://github.com/dfm/jax-finufft
cd jax-finufft
python -m pip install .

Not sure about the specs of the server but I can try to find out. I'll also try to just pip install directly and see if that works

**Comment by dfm** [comment]
Thanks. I assume that the server is some flavor of linux?

If the `pip install jax-finufft` doesn't work, please run the following commands in your `jax-finufft` directory and share the full output here:

```bash
rm -rf build _skbuild
python -m pip install -v -e .
```

**Comment by samaktbo** [comment]
I used pip and everything works. thanks a bunch :)
